"""empty message

Revision ID: 402a3ceacf73
Revises: 
Create Date: 2020-04-08 18:47:00.415349

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '402a3ceacf73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.Text(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('deployed', sa.TIMESTAMP(), nullable=True),
    sa.Column('retrieved', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('deployment', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('level', sa.Numeric(), nullable=True),
    sa.Column('water_temp', sa.Numeric(), nullable=True),
    sa.Column('air_temp', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('pressure', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['deployment'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('deployment', 'time')
    )
    #op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('measurement')
    op.drop_table('deployment')
    # ### end Alembic commands ###
