"""empty message

Revision ID: 794f823b4c36
Revises: 62a7bb357ca7
Create Date: 2020-04-16 16:14:36.270927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794f823b4c36'
down_revision = '62a7bb357ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('spatial_ref_sys')
    op.add_column('deployment', sa.Column('url', sa.Text(), nullable=True))
    #op.drop_index('idx_deployment_location', table_name='deployment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_deployment_location', 'deployment', ['location'], unique=False)
    op.drop_column('deployment', 'url')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
